---
- name: 'update apt packages.'
  become: true
  yum:
    update_cache: yes

- name: 'Upgrade packages'
  become: true
  yum:
    upgrade: yes

- name: 'Remove dependencies that are no longer required'
  become: true
  apt:
    autoremove: yes