---
# main
- name: Installing Docker and docker Compose on Spire Dashboard Server   
  # Use the public IP if the VM is already created
  hosts: all
  # For Ubuntu instances, the user will be `ubuntu`
  # For Amazon LInux 2 instance, the user will be `ec2-user`
  remote_user: root
  become: true
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: 'wait 2 seconds for target connection to become reachable/usable.'
      wait_for_connection:
        timeout: 2
    - name: 'Install python for Ansible.'
      become: true
      raw: test -e /usr/bin/python3 || (yum -y update && yum install -y python3)
      changed_when: false

  roles:
   - docker
   - upgrade-packages
   

  